### ISSUE TITLE
DOC: Add Metric Interpretation section to Overview

### ISSUE THREAD

**Issue by KavlinClein** [PEOPLE-ER/Spectral-Recovery#65]
**The problem**
The tool Documentation does a good job of describing the indexes and metrics that the tool uses. However, what is missing is a section helping the user interpret the values returned by different recovery metrics.

**Describe the solution you'd like**
A short paragraph per recovery metric explaining how to interpret the different recovery metrics.
Something like:

"Interpretation of R80P values is similar to the RRI, with a value of zero indicating that spectral forest recovery did not occur, while a value of one indicates that NBR values have recovered to be equivalent to 80% of the pre-disturbance values. Values greater than one indicate that spectral forest recovery has exceeded that of the 80% of pre-disturbance threshold" (Frazier et al., 2018).

**Comment by szwiep** [comment]
Will be addressed by #97
