### ISSUE TITLE
DOC: Documentation Update

### ISSUE THREAD

**Issue by KavlinClein** [PEOPLE-ER/Spectral-Recovery#97]
**Overall Updates:**

-Landing Page ReadMe:
  -Update Workflow Diagram
- Update API Reference
- User Guide:
  - Rename -> Theoretical Basis
  - Split into three documents per section
  -  Ensure subsections are up to date
  - Update Section 2:
    - Tool Workflow Diagram
    - Add reference to spyndex reword our index list to be 'commonly used indexes'
    - Put a reminder or something to update the Restoration Polygon once the multi-polygon task has been finalized

**Tutorial Updates:**

- Rename tab to Tutorials
- 2 Subsections:
  - For Users:
    - Getting Started:
      - Reworked Problem Statement
      - Installation
      - Quick Overview
    - User Guide:
      - Terminology
      - Reading in Data
      - Computing Indeces (Reference to Reading in Data, about bands and stuff):
        - Make sure to include a paragraph on scaling data (mention that some metrics expect data to be between 0 and 1 and therefore if some data is not scaled it might lead to unexpected outputs) (YrYrr, RRI, dNBR).
      - Recovery Targets:
        - Recovery Targets (Historic vs Reference)
        - Historic recovery methods (Windowed, per-pixel, etc.)
      - Plotting
      - Recovery Metrics:
        - General information about recovery metrics
        - Interpretation of the metrics.
      - Computing with Numpy vs Dask
  - For Developers (WIP):
    - Contributing
    - Restoration Area description 
    - System architecture diagram
    - Evolution Roadmap

**Documentation Structure (WIP):**

**Comment by szwiep** [comment]
I think we should also have a tutorial that show's the tool ability to integrate with some cloud-native image processing workflows? i.e using results from a odc.stac median composite operation, or retrieving polygons from a public server?

**Comment by KavlinClein** [comment]
Great idea, completely agree.
